

#' loop function to change the color pixel by pixel
#' #' default setting grey filter
#' create a new object for the return e.g. new_obj <- pixelchange()
#' use magick::fun to export the new_obj
#'
#' @param ori_bitmap the raw() vector generated by readImage
#' @param colorscale  the filter you want to apply
#'
#' @return raw() vector of the new image with the filter chosen
#'
#' @example path.R
#'
pixelchange <- function (ori_bitmap=image_bitmap, colorscale="grey", output="FALSE") {
  if (colorscale!="grey" && colorscale!="red" && colorscale!="green" && colorscale!="blue" ){
    return("Filter doesn't exist")
  }
  width = length (ori_bitmap [1, ,1])
  height = length (ori_bitmap [1, 1,])
  new_image <-array(as.raw(0), dim=c (3, width, height))
  if (colorscale=="grey"){#choose filter
    for (i in 1:width) {
      for (j in 1:height) {#use loop to change pixel by pixel
        new_image [1, i, j] <- grey(i,j,ori_bitmap)
        new_image [2, i, j] <- grey(i,j,ori_bitmap)
        new_image [3, i, j] <- grey(i,j,ori_bitmap)
      }
    }
  }else if(colorscale=="red"){
    for (i in 1:width) {
      for (j in 1:height) {
        new_image [1, i, j] <- red(i,j,ori_bitmap)
        new_image [2, i, j] <- as.raw(0x00)
        new_image [3, i, j] <- as.raw(0x00)
      }
    }
  }else if (colorscale=="green"){
    for (i in 1:width) {
      for (j in 1:height) {
        green(i,j,ori_bitmap)
        new_image [1, i, j] <- as.raw(0x00)
        new_image [2, i, j] <- green(i,j,ori_bitmap)
        new_image [3, i, j] <- as.raw(0x00)
      }
    }
  }else if (colorscale=="blue"){
    for (i in 1:width) {
      for (j in 1:height) {
        blue(i,j,ori_bitmap)
        new_image [1, i, j] <- as.raw(0x00)
        new_image [2, i, j] <- as.raw(0x00)
        new_image [3, i, j] <- blue(i,j,ori_bitmap)
      }
    }
    }
  if (output=="TRUE"){image_write(image_read(new_image), path = "figures/output.jpg", format = "jpg", quality = 95)
  }#output or not based on the choice
  return(image_read(new_image))#return the picture
}
